title: faelsfernandes.me
description: > # this means to ignore newlines until "baseurl:"
  Cyber Security Analyst & Red Team
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rafael Fernandes # add your name
author-img: rafael-fernandes.jpg # add your photo
about-author: I am a Cyber Security Analyst and Red Team man trying to get some bounties. # add description
social-twitter: faelsfernandes # add your Twitter handle
#social-facebook: # add your Facebook handle
social-hackerone: faelsfernandes
social-github: faelsfernandes # add your Github handle
social-linkedin: faelsfernandes # add your Linkedin handle
social-email: faelsfernandes@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
